spring.application.name=trainer-workload-service
server.port=8081

app.security.jwt.secret=Z3ltQ1JNLXNlY3VyaXR5LWp3dC1zZWNyZXQtbXVzdC1iZS1hdC1sZWFzdC0zMi1ieXRlcy1sb25n

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - [%thread] %-5level %logger{36} - %msg%n
management.endpoints.web.exposure.include=health,info,prometheus
